CREATE DATABASE bas;

CREATE TABLE `bas`.`tb` (`id` INT NOT NULL AUTO_INCREMENT , `nom` VARCHAR(25) NOT NULL , `prenom` VARCHAR(50) NOT NULL , `mdp` VARCHAR(8) NOT NULL , PRIMARY KEY (`id`)) ENGINE = MyISAM;
